
spring:

  # Database Settings
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:security;MODE=MySQL
    username: chris
    password: chris0331!
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect  #???? DB? ?? ??
    show-sql: true
    hibernate:
      ddl-auto: update

  # Security Settings
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 982584669219-e10m26017r88bn1hbke4jeglb2gasiek.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 1097641094424105
            client-secret: 4546596e8fb0b2b819c65972ca2c2f98
            scope:
            - email
            - public_profile

          kakao:
            client-id: ba4ff23b0b05571d20cc140bd73e416e
            # http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao

          naver:
            client-id: UfvEsWBUbXEa18DE0hBa
            client-secret: Rl3wblw4uy
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response #회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.


