
spring:

  # Database Settings
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:security;MODE=MySQL
    username: chris
    password: chris0331!
    driver-class-name: org.h2.Driver
